# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 1b954f09e1201bb2e5718daaed2136ae4eba541ed3e0474ca5eb57ae78c749c83a56a859ff1b08cafbc3d2998de2c5824ef5b5ee796d599856bc42f9ff5d8d1a

test:
  secret_key_base: a8f7990279ebab849369d5816701d82cf2348033a35b3ac8b0d9a9eec26de677fd4ea362202619d56c5cb0b77a51ffec072284f7ca1aa707e2fb44d616825806

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
